### ISSUE TITLE
Account key not found when requesting new cert or renew existing cert

### ISSUE THREAD

**Issue by MarcelKoen** [avinetworks/devops#267]
### [letsencrypt_mgmt_profile](https://github.com/avinetworks/devops/blob/master/cert_mgmt/letsencrypt_mgmt_profile.py/)

We are using this script for a year now. Currently on version 0.97. It was working fine. Just recently, after upgrading from AVI version 20.1.4 to 21.1.4-2p6 we got rate limited by LE "...too many registrations for this IP..." and eventually, they are blocking further requests.

We checked the logs and every time a cert renew is triggered, the message "....\nDEBUG: API Host is '172.17.0.1'\nAccount key not found. Generating account key...\nParsing account key...\....." appears, followed by "...\nRegistering account...\nRegistered!...."  and then further down the actual error: 
".... Response Code: 429 Response: {'type': 'urn:ietf:params:acme:error:rateLimited', 'detail': '**Error creating new account :: **too many registrations** for this IP**: see https://letsencrypt.org/docs/too-many-registrations-for-this-ip/', 'status': 429} Error in sys.excepthook: Traceback (most recent call last): File "/usr/local/lib/python3.8/dist-packages/avi_traceback/avi_exception_hook.py", line 51, in avi_excepthook os.makedirs(output_dir) File "/usr/lib/python3.8/os.py", line 223, in makedirs mkdir(name, mode) OSError: [Errno 30] **Read-only file system:** '/var/lib/avi/python_crash' Original exception was: Traceback (most recent call last): File "/run/shm/cs/lets-encrypt-certificate-mgmt", line 554, in <module> cert = certificate_request(csr, common_name, kwargs) File "/run/shm/cs/lets-encrypt-certificate-mgmt", line 530, in certificate_request signed_crt = get_crt(user, password, tenant, api_version, csr_temp_file.name, File "/run/shm/cs/lets-encrypt-certificate-mgmt", line 222, in get_crt account, code, acct_headers = _send_signed_request(directory['newAccount'], reg_payload, "Error registering") File "/run/shm/cs/lets-encrypt-certificate-mgmt", line 121, in _send_signed_request return _do_request(url, data=data.encode('utf8'), err_msg=err_msg, depth=depth) File "/run/shm/cs/lets-encrypt-certificate-mgmt", line 107, in _do_request raise ValueError("{0}:\nUrl: {1}\nData: {2}\nResponse Code: {3}\nResponse: {4}".format(err_msg, url, data, code, resp_data)) ValueError: Error registering: Url: https://acme-staging-v02.api.letsencrypt.org/acme/new-acct Data: b'{"protected":..."

Now I am wondering, why suddenly, after the version upgrade, it starts behaving like this.

**Comment by MarcelKoen** [comment]
Generating an 4096 bit RSA key and storing it in the certificate management profile under parameter "letsencrypt_key" fixed the issue for me.

**Comment by patschi** [comment]
The private key used to be persisted on a path on the Avi Controller. But in recent version the Control Scripts were sandboxed in containers, so they cannot be persisted anymore. That's why it was moved to `letsencrypt_key` variable as you figured out.

However to note, having the private key to be re-generated is not an issue per-se. It will take longer time to generate, will invalidate TLSA DNS records most likely, but won't block you from issuing new certificates.

If your IP was blocked for too many registrations from LetsEncrypt, I'd suggest checking previous logs on how often and why those certificate requests failed and go on from there.
